# This file is used by actions/labeler to automaticanyy label pull requests.

ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/workflows/**"
          - ".github/actions/**"
          - ".github/labeler.yaml"
          - ".github/labels.yaml"

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**"
          - "**/README.md"
          - "**/CHANGELOG.md"

tests:
  - changed-files:
      - any-glob-to-any-file:
          - "**/tests/**"
          - "**/test/**"
          - "**/spec/**"
          - "**/specs/**"
          - "**/test.ts"
          - "**/spec.ts"
          - "**/test.tsx"
          - "**/spec.tsx"

example:
  - changed-files:
      - any-glob-to-any-file:
          - "example/**"

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - "**/package.json"
          - "**/package-lock.json"
          - "**/yarn.lock"
          - "**/pnpm-lock.yaml"

core:
  - changed-files:
      - any-glob-to-any-file:
          - "lib/src/**"
