# This file is used by actions/labeler to automaticanyy label pull requests.

ci:
  - any:
      - changed_files:
          - AnyGlobToAnyFile:
              - .github/workflows/**
              - .github/actions/**
              - .github/labeler.yaml
              - .github/labels.yaml

documentation:
  - any:
      - changed_files:
          - AnyGlobToAnyFile:
              - "**/README.md"
              - "docs/**"

tests:
  - any:
      - changed_files:
          - AnyGlobToAnyFile:
              - "**/*.test.ts"
              - "**/*.spec.ts"
              - "**/*.test.tsx"
              - "**/*.spec.tsx"

example:
  - any:
      - changed_files:
          - AnyGlobToAnyFile:
              - "example/**"

dependencies:
  - any:
      - changed_files:
          - AnyGlobToAnyFile:
              - "**/package.json"
              - "package-lock.json"

core:
  - any:
      - changed_files:
          - AnyGlobToAnyFile:
              - "lib/src/**"
