ci:
  - .github/workflows/**
  - .github/actions/**
  - .github/labeler.yaml
  - .github/labels.yaml

documentation:
  - "**/README.md"
  - "docs/**"

tests:
  - "**/*.test.ts"
  - "**/*.spec.ts"
  - "**/*.test.tsx"
  - "**/*.spec.tsx"

example:
  - "example/**"

dependencies:
  - "**/package.json"
  - "package-lock.json"

core:
  - "lib/src/**"
