name: "Lint"
description: "Lint the code in the repo, check for unused files, dependencies, and exports"

inputs:
  check-commits:
    description: "Check if the commits follow the conventional commits specification"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Lint
      run: pnpm run lint
      shell: bash

    - name: Typecheck
      run: pnpm run typecheck
      shell: bash

    - name: Format
      run: pnpm run format
      shell: bash

    - name: Check for unused files, dependencies, and exports
      run: pnpm run knip
      shell: bash

    - name: Lint commits
      if: ${{ inputs.check-commits == 'true' }}
      run: pnpm run lint:commits
      shell: bash

    - name: Check lib exports
      run: pnpm -C lib run lint:exports
      shell: bash
