name: Label Pull Requests

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  label-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Add Labels for PR
        uses: actions/labeler@v5
        with:
          configuration-path: ".github/labeler.yaml"
