name: Sync labels

# This workflow synchronizes labels in the repository with the labels defined in .github/labels.yaml.

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/labels.yaml

permissions:
  issues: write

jobs:
  sync-labels:
    runs-on: ubuntu-24.04 # pinned for determinism
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false
      - name: Sync labels
        uses: EndBug/label-sync@52074158190acb45f3077f9099fea818aa43f97a # v2.3.3
        with:
          config-file: .github/labels.yaml
          delete-other-labels: false
          token: ${{ secrets.GITHUB_TOKEN }}
